# Generated by Django 3.0.3 on 2020-05-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anketa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('vorname', models.CharField(blank=True, max_length=50)),
                ('fathername', models.CharField(blank=True, max_length=50)),
                ('gender', models.IntegerField(choices=[(0, 'MALE'), (1, 'FEMALE')], default=0)),
                ('age', models.IntegerField(default=33)),
                ('urlVK', models.CharField(default='123123', max_length=50)),
            ],
        ),
    ]
