# Generated by Django 3.0.3 on 2020-05-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anketa',
            name='idVK',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
