# Generated by Django 3.0.3 on 2020-04-27 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('vorname', models.CharField(blank=True, max_length=50)),
                ('fathername', models.CharField(blank=True, max_length=50)),
                ('gender', models.IntegerField(choices=[(0, 'MALE'), (1, 'FEMALE')], default=0)),
                ('age', models.IntegerField(default=18)),
                ('position', models.CharField(blank=True, max_length=50)),
                ('status', models.IntegerField(choices=[(0, 'Сотрудник'), (1, 'Руководитель среднего звена'), (2, 'Руководитель высшего звена'), (3, 'Директор'), (3, 'Админ')], default=0)),
                ('exp', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
