# Generated by Django 3.0.3 on 2020-04-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200427_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='isFull',
            field=models.BooleanField(default=False),
        ),
    ]
