# Generated by Django 3.0.3 on 2020-04-27 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200427_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
    ]
