# Generated by Django 3.0.3 on 2020-04-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200427_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='C:\\Users\\Федор\\Documents\\GIT\\Smart_City/static/images/avatars/default.png', null=True, upload_to='C:\\Users\\Федор\\Documents\\GIT\\Smart_City/static/images/avatars/', verbose_name='profile picture'),
        ),
    ]
