# Generated by Django 3.0.3 on 2020-05-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200430_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='message',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
