# Generated by Django 3.0.3 on 2020-04-28 12:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idDevice', models.IntegerField(unique=True)),
                ('danger_temp', models.FloatField(default=45)),
                ('critical_temp', models.FloatField(default=50)),
                ('danger_vibr', models.FloatField(default=0.75)),
                ('critical_vibr', models.FloatField(default=1)),
                ('danger_pow', models.IntegerField(default=0.65)),
                ('critical_pow', models.IntegerField(default=0.7)),
                ('danger_load', models.FloatField(default=80)),
                ('critical_load', models.FloatField(default=95)),
                ('danger_time', models.IntegerField(default=70000)),
                ('critical_time', models.IntegerField(default=80000)),
            ],
        ),
        migrations.CreateModel(
            name='StatData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2000, 1, 1, 10, 10, 10), unique=True)),
                ('temp', models.FloatField(default=30)),
                ('vibration', models.FloatField(default=0)),
                ('power', models.FloatField(default=0)),
                ('load', models.FloatField(default=0)),
                ('time', models.IntegerField(default=0)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='telemetry.Device')),
            ],
        ),
    ]
