# Generated by Django 3.0.3 on 2020-04-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0002_device_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='idDevice',
            field=models.IntegerField(),
        ),
    ]
