# Generated by Django 3.0.3 on 2020-04-28 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0003_auto_20200428_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='idDevice',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='statdata',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telemetry.Device'),
        ),
    ]
