# Generated by Django 3.0.3 on 2020-04-30 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0005_approx'),
    ]

    operations = [
        migrations.AddField(
            model_name='approx',
            name='device',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='telemetry.Device'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='approx',
            name='param',
            field=models.CharField(default='time', max_length=20),
            preserve_default=False,
        ),
    ]
