# Generated by Django 3.0.3 on 2020-05-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0006_auto_20200501_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='approx',
            name='cur_value',
            field=models.FloatField(default=0),
        ),
    ]
