# Generated by Django 3.0.3 on 2020-05-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0007_approx_cur_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary_Approx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bench', models.CharField(default='bench', max_length=20)),
                ('vibration', models.FloatField(default=0)),
                ('vibrationp', models.FloatField(default=0)),
                ('load', models.FloatField(default=0)),
                ('loadp', models.FloatField(default=0)),
                ('temp', models.FloatField(default=0)),
                ('tempp', models.FloatField(default=0)),
            ],
        ),
    ]
