# Generated by Django 3.0.3 on 2020-05-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0009_auto_20200501_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='approx',
            name='time_out',
            field=models.IntegerField(default=0),
        ),
    ]
